accounts:
- '496598440491'
archive_name: Temp-s3/iac/dev/dryrun/archive.zip
asset_insight_id: '206296'
deployment_engine_version: 3.2.16
environment_order:
- dev
github_branch: main
github_owner: SakshiKendreTR
github_repo: SakshiKendreTR/Temp
log_retention: 90
project_code: a206296-s3-deployment-temp
project_name: temp
region: us-east-1
resource_owner: sakshi.kendre@thomsonreuters.com
service_name: s3-deployment
source_bucket: a206296-tr-ihn-sandbox-us-east-1-source
template_bucket_name: a206296-tr-ihn-sandbox-us-east-1-source
template_key_prefix: Temp-s3/template
